"""Initial migration

Revision ID: ff6b273e67dc
Revises: 
Create Date: 2025-12-06 16:33:27.644454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6b273e67dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='쿠폰 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='쿠폰명'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='쿠폰 설명'),
    sa.Column('discount_rate', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='할인율 (%)'),
    sa.Column('start_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='시작 일시'),
    sa.Column('end_at', sa.DateTime(), nullable=False, comment='종료 일시'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='사용자 고유 ID'),
    sa.Column('role', sa.Enum('CUSTOMER', 'SELLER', 'ADMIN', name='userrole'), nullable=False, comment='사용자 역할 (CUSTOMER, SELLER, ADMIN)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일 (로그인 ID)'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='비밀번호 (암호화)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='이름'),
    sa.Column('birth_date', sa.Date(), nullable=False, comment='생년월일'),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False, comment='성별'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='주소'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='도서 고유 ID'),
    sa.Column('seller_id', sa.Integer(), nullable=False, comment='판매자 ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='도서명'),
    sa.Column('author', sa.String(length=100), nullable=False, comment='저자'),
    sa.Column('publisher', sa.String(length=100), nullable=False, comment='출판사'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='요약 설명'),
    sa.Column('isbn', sa.String(length=20), nullable=False, comment='ISBN 코드'),
    sa.Column('price', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='판매가'),
    sa.Column('publication_date', sa.Date(), nullable=False, comment='출판일'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='등록일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    op.create_index(op.f('ix_books_seller_id'), 'books', ['seller_id'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='주문 ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='주문자 ID'),
    sa.Column('total_price', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='총 결제 금액'),
    sa.Column('status', sa.Enum('CREATED', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELED', name='orderstatus'), nullable=False, comment='주문 상태'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='주문 생성일'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='주문 수정일'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Refresh Token 고유 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='토큰 사용자 ID'),
    sa.Column('token', sa.String(length=500), nullable=False, comment='발급된 Refresh Token 문자열'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='토큰 생성시간'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='토큰 정보 수정시간'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='사용자 쿠폰 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('coupon_id', sa.Integer(), nullable=False, comment='쿠폰 ID'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='사용 여부'),
    sa.Column('used_at', sa.DateTime(), nullable=True, comment='사용 일시'),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='발급 일시'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_coupons_coupon_id'), 'user_coupons', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_user_coupons_user_id'), 'user_coupons', ['user_id'], unique=False)
    op.create_table('books_view',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='조회 기록 ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='조회한 사용자 (비로그인 가능)'),
    sa.Column('book_id', sa.Integer(), nullable=False, comment='조회된 도서'),
    sa.Column('viewed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='조회 일시'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_view_book_id'), 'books_view', ['book_id'], unique=False)
    op.create_index(op.f('ix_books_view_user_id'), 'books_view', ['user_id'], unique=False)
    op.create_table('carts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='장바구니 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('book_id', sa.Integer(), nullable=False, comment='도서 ID'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='수량'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='삭제 여부 (통계용)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 일시'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_book_id'), 'carts', ['book_id'], unique=False)
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='즐겨찾기 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('book_id', sa.Integer(), nullable=False, comment='도서 ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='삭제 여부 (통계용)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 일시'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_book_id'), 'favorites', ['book_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='주문 상세 ID'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='주문 ID'),
    sa.Column('book_id', sa.Integer(), nullable=True, comment='도서 ID'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='수량'),
    sa.Column('price_at_purchase', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='구매 당시 도서 가격'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='리뷰 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='작성자 ID'),
    sa.Column('book_id', sa.Integer(), nullable=False, comment='리뷰 대상 도서'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='실제 구매한 주문 ID'),
    sa.Column('comment', sa.Text(), nullable=False, comment='리뷰 내용'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='평점 (1~5)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='작성일'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_book_id'), 'reviews', ['book_id'], unique=False)
    op.create_index(op.f('ix_reviews_order_id'), 'reviews', ['order_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='댓글 ID'),
    sa.Column('review_id', sa.Integer(), nullable=False, comment='댓글이 달린 리뷰 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='작성자 ID'),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True, comment='NULL이면 일반 댓글, 값이 있으면 대댓글'),
    sa.Column('content', sa.Text(), nullable=False, comment='댓글 내용'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='작성일'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_review_id'), 'comments', ['review_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('review_like_counts',
    sa.Column('review_id', sa.Integer(), nullable=False, comment='리뷰 ID'),
    sa.Column('like_count', sa.Integer(), nullable=False, comment='좋아요 수 캐시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='마지막 업데이트 일시'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('review_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='리뷰 좋아요 ID'),
    sa.Column('review_id', sa.Integer(), nullable=False, comment='좋아요 대상 리뷰 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='좋아요 누른 사용자 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='좋아요 일시'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'user_id', name='unique_review_like')
    )
    op.create_index(op.f('ix_review_likes_review_id'), 'review_likes', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_likes_user_id'), 'review_likes', ['user_id'], unique=False)
    op.create_table('comment_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='댓글 좋아요 ID'),
    sa.Column('comment_id', sa.Integer(), nullable=False, comment='좋아요 대상 댓글 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='좋아요 누른 사용자 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='좋아요 일시'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='unique_comment_like')
    )
    op.create_index(op.f('ix_comment_likes_comment_id'), 'comment_likes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_likes_user_id'), 'comment_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_likes_user_id'), table_name='comment_likes')
    op.drop_index(op.f('ix_comment_likes_comment_id'), table_name='comment_likes')
    op.drop_table('comment_likes')
    op.drop_index(op.f('ix_review_likes_user_id'), table_name='review_likes')
    op.drop_index(op.f('ix_review_likes_review_id'), table_name='review_likes')
    op.drop_table('review_likes')
    op.drop_table('review_like_counts')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_review_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_order_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_book_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_book_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_book_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_books_view_user_id'), table_name='books_view')
    op.drop_index(op.f('ix_books_view_book_id'), table_name='books_view')
    op.drop_table('books_view')
    op.drop_index(op.f('ix_user_coupons_user_id'), table_name='user_coupons')
    op.drop_index(op.f('ix_user_coupons_coupon_id'), table_name='user_coupons')
    op.drop_table('user_coupons')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_seller_id'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('coupons')
    # ### end Alembic commands ###
